import { KlipperConfigHelper } from '@/server/helpers/klipper-config';
import { PrinterConfiguration } from '@/zods/printer-configuration';
export const template = (config: PrinterConfiguration, helper: KlipperConfigHelper) => `
# WARNING. THIS FILE IS GENERATED BY THE RATOS CONFIGURATOR.
# CHANGES YOU MAKE HERE WILL BE OVERWRITTEN. KEEP YOUR CHANGES IN PRINTER.CFG.
# Config generated for ${config.printer.manufacturer} ${config.printer.name} ${config.size}
# Documentation: https://os.ratrig.com

#############################################################################################################
### CONTROLBOARD & TOOLBOARD
#############################################################################################################
${helper.renderBoards()}

[board_pins btt-octopus-11-extra]
aliases:
  #----------------------------------------- DUAL_CARRIAGE motor pins -----------------------------------------
  # Assigned to slot: "MOTOR 7"
  #------------------------------------------------------------------------------------------------------------
  dual_carriage_step_pin=PE6,
  dual_carriage_dir_pin=PA14,
  dual_carriage_enable_pin=PE0,
  dual_carriage_uart_pin=PD3,
  dual_carriage_diag_pin=PG15,
  dual_carriage_endstop_pin=PG15,
  
  #------------------------------------------- EXTRUDER1 motor pins --------------------------------------------
  # Assigned to slot: "MOTOR 4"
  #------------------------------------------------------------------------------------------------------------
  e1_step_pin=PF9,
  e1_dir_pin=PF10,
  e1_enable_pin=PG2,
  e1_uart_pin=PF2,
  
  #----------------------------------------------- GENERAL PINS -----------------------------------------------
  e1_heater_pin=PA3, 
  e1_sensor_pin=PF5,
  fan_part_cooling_e1_pin=PD13,
  fan_toolhead_cooling_e1_pin=PD14

#############################################################################################################
### BASE SETUP
#############################################################################################################
${helper.renderBase()}
[include RatOS/printers/v-cast-idex/v-cast-idex.cfg]
[include RatOS/printers/v-cast-idex/macros.cfg]

# Extruder
${helper.renderExtruder()}
# T1 Phaetus Apus definition (from RatOS/extruders/phaetus-apus.cfg)
[extruder1]
rotation_distance: 4.263
full_steps_per_rotation: 200
filament_diameter: 1.750
max_extrude_only_velocity: 60

[firmware_retraction]
retract_speed: 60
unretract_extra_length: 0
unretract_speed: 60

# Hotend
${helper.renderHotend()}
# T1 DropEffect XG definition (from RatOS/hotends/dropeffect-xg.cfg)
[extruder1]
max_extrude_only_distance: 200
nozzle_diameter: 0.4
heater_pin: PA3
sensor_type: ATC Semitec 104NT-4-R025H42G
sensor_pin: PF5
min_extrude_temp: 170
min_temp: 0
max_temp: 295
pressure_advance: 0.03

[firmware_retraction]
retract_length: 0.5

# ADXL345 resonance testing configuration
${helper.renderInputShaper(config.size)}

#############################################################################################################
### STEPPER MOTORS, DRIVERS & SPEED LIMITS
#############################################################################################################
${helper.renderMotorSections()}
#---------------------------------------------------- DUAL_CARRIAGE -----------------------------------------
# The DUAL_CARRIAGE axis motor moves the right print head left and right.
# Connected to MOTOR 7 on BIGTREETECH Octopus V1.1 F446
# Driver: BTT TMC2209 v1.3
# Motor: LDO-42STH48-2504AC
# Voltage: 24
#------------------------------------------------------------------------------------------------------------
[tmc2209 dual_carriage]
stealthchop_threshold: 0
interpolate: False
uart_pin: PD3
run_current: 1.1
driver_TBL: 1
driver_TOFF: 3
driver_HEND: 0
driver_HSTRT: 0
sense_resistor: 0.11

[dual_carriage]
axis: x
step_pin: PE6
dir_pin: PA14
enable_pin: !PE0
microsteps: 64
full_steps_per_rotation: 200
rotation_distance: 40
homing_speed: 50
#------------------------------------------------- EXTRUDER1 -------------------------------------------------
# The extruder motor used for pushing filament through the right toolhead (T1)
# Connected to MOTOR 7 on BIGTREETECH Octopus V1.1 F446
# Driver: BTT TMC2209 v1.3
# Motor: LDO-36STH20-1004AHG
# Voltage: 24
#------------------------------------------------------------------------------------------------------------
[tmc2209 extruder1]
stealthchop_threshold: 0
interpolate: False
uart_pin: PF2
run_current: 0.707
driver_TBL: 0
driver_TOFF: 4
driver_HEND: 6
driver_HSTRT: 7
sense_resistor: 0.11

[extruder1]
step_pin: PF9
dir_pin: PF10
enable_pin: !PG2
microsteps: 64
full_steps_per_rotation: 200
rotation_distance: 4.263


${helper.renderSpeedLimits()}

[bed_mesh]
speed: ${helper.getMacroTravelSpeed()}

[z_tilt]
speed: ${helper.getMacroTravelSpeed()}


#############################################################################################################
### HOMING
#############################################################################################################
${helper.renderProbeIncludes()}
${helper.renderEndstopSection()}

# Physical DUAL_CARRIAGE endstop configuration
[dual_carriage]
endstop_pin: PG15
[gcode_macro RatOS]
variable_homing_x: "endstop"

#############################################################################################################
### FANS
#############################################################################################################
${helper.renderFans()}

# Multiple toolheads with part cooling fans configured
# [fan] will use an unused io pin, proxy m106 settings to active toolhead via macro.
# Part cooling fan
[fan]
pin: rpi:gpio4         # sacrifical part fan, use this to independently control your both toolhead part fans
[fan_generic part_fan_t0]
# 2-pin fan connected to 2-pin header on Octopus V1.1 F446 - input voltage pwm
pin: PA8
[fan_generic part_fan_t1]
# 2-pin fan connected to 2-pin header on Octopus V1.1 F446 - input voltage pwm
pin: PD13

[heater_fan toolhead_cooling_fan_t1]
heater: extruder1
# 2-pin fan connected to 2-pin header on Octopus V1.1 F446 - input voltage pwm
pin: PD14

#############################################################################################################
### MACRO CONFIGURATION
#############################################################################################################
${helper.renderMacros()}

[gcode_macro T0]
variable_has_oozeguard: False
variable_loading_position: -25                            # filament load x position
variable_parking_position: -50                            # parking x position
variable_resume_after_insert: True                        # resumes the print after inserting new filament

[gcode_macro T1]
variable_join: 0
variable_remap: 0
variable_alert: ""
variable_filament_name: ""
variable_filament_type: ""
variable_filament_temp: 0
variable_runout_sensor: ""
variable_active: False
variable_color: "0ea5e9"                                  # Used in frontends
variable_hotend_type: "SF"
variable_has_cht_nozzle: False
variable_cooling_position_to_nozzle_distance: 40          # heatbreak length from cold zone to nozzle
variable_tooolhead_sensor_to_extruder_gear_distance: 15    # distance in mm from the sensor to the extruder gear
variable_extruder_gear_to_cooling_position_distance: 30   # distance in mm from the extruder gear to the end of the hotend cold zone
variable_filament_loading_nozzle_offset: -5
variable_filament_grabbing_length: 5
variable_filament_grabbing_speed: 1
variable_enable_insert_detection: True                    # enables filament sensor insert detection 
variable_enable_runout_detection: True                    # enables filament sensor runout detection 
variable_enable_clog_detection: True                      # enables filament sensor clog detection 
variable_unload_after_runout: True                        # unload filament after a runout has been detected
variable_purge_after_load: 0
variable_purge_before_unload: 0
variable_extruder_load_speed: 60
variable_filament_load_speed: 10
variable_standby: False
variable_temperature_offset: 0                            # hotend temperature offset
variable_has_oozeguard: False                             # toolhead has a oozeguard
variable_has_front_arm_nozzle_wiper: False                # toolhead has front arm nozzle wipers
variable_loading_position: 330.1                          # filament load x position
variable_parking_position: 355.1                          # parking x position
variable_resume_after_insert: True                        # resumes the print after inserting new filament
gcode:
	{% set x = params.X|default(-1.0)|float %}
	{% set y = params.Y|default(-1.0)|float %}
	{% set z = params.Z|default(0.0)|float %}
	{% set s = params.S|default(1)|int %}
	{% if printer["gcode_macro _SELECT_TOOL"] is defined %}
		_SELECT_TOOL T=1 X={x} Y={y} Z={z} TOOLSHIFT={s}
	{% endif %}

[gcode_macro T1]
variable_has_oozeguard: False

# Macro variable overrides
[gcode_macro RatOS]
${helper.renderMacroVariableOverrides()}
variable_toolchange_travel_speed: 300                                  # parking travel speed
variable_toolchange_travel_accel: 3000  
variable_default_toolhead: 0                           # the toolhead with the z-probe, 0=left 1=right toolhead
variable_shaper_x_freq: [58.2, 58.2, 58.2, 58.2]       # shaper frequency [T0, T1, COPY, MIRROR]
variable_shaper_y_freq: [29, 29, 29, 29]               # shaper frequency [T0, T1, COPY, MIRROR]
variable_shaper_x_type: ["mzv", "mzv", "mzv", "mzv"]   # shaper frequency algorythm [T0, T1, COPY, MIRROR]
variable_shaper_y_type: ["mzv", "mzv", "mzv", "mzv"]   # shaper frequency algorythm [T0, T1, COPY, MIRROR]

# Save variables
${helper.renderSaveVariables({
	xcontrolpoint: config.size.x / 2 - 50,
	ycontrolpoint: config.size.y + 25,
	zcontrolpoint: 10,
	zoffsetcontrolpoint: 5,
})}

[gcode_macro _VAOC]
variable_expected_camera_x_position: ${config.size.x / 2 - 50}
variable_expected_camera_y_position: ${config.size.y + 25}
`;

export const initialPrinterCfg = (config: PrinterConfiguration, helper: KlipperConfigHelper) => `
#############################################################################################################
### CONFIGURATION GENERATED BY THE RATOS CONFIGURATOR
### Everything below [include RatOS.cfg] will override default RatOS behavior
#############################################################################################################
[include RatOS.cfg]

#############################################################################################################
### MACRO CONFIGURATION
### Configure the behavior of RatOS macros
### See: https://os.ratrig.com/docs/configuration/macros
#############################################################################################################
[gcode_macro RatOS]
variable_relative_extrusion: True
variable_preheat_extruder: True
variable_calibrate_bed_mesh: True
variable_nozzle_priming: "primeblob"
variable_start_print_park_in: "front"
variable_start_print_park_z_height: 50
variable_end_print_park_in: "back"
variable_pause_print_park_in: "front"

#############################################################################################################
### USER OVERRIDES & CUSTOM CONFIGURATION
### Anything custom you want to add, or RatOS configuration you want to override, do it here.
### This section is pre-populated with the most common settings you may want to change.
### See: https://os.ratrig.com/docs/configuration/includes-and-overrides
###
### It is recommended that you follow these steps to properly calibrate your printer:
### 0) Sanity check and PID Tuning: https://www.klipper3d.org/Config_checks.html
### 1) ${helper.renderZOffsetGuidance('###    ')}
### 2) Pressure Advance: https://www.klipper3d.org/Pressure_Advance.html
### 3) Skew Correction: https://www.klipper3d.org/Skew_Correction.html
### 4) Resonance Compensation: https://www.klipper3d.org/Resonance_Compensation.html
### RatOS has dedicated macro's to generate shaper graphs for deeper analysis (requires accelerometer).
### Use GENERATE_SHAPER_GRAPHS to generate the resonance graphs for analysing and manually entering input 
### shaper configuration.
### You can run SHAPER_CALIBRATE to automatically calibrate your input shaper configuration, if you just want
### to get started.
### Additionally, you can use the Realtime Analysis Tool to analyze your printer's performance in real-time.
### Read more about klipper here: https://www.klipper3d.org/Overview.html
#############################################################################################################

${helper.renderUserStepperSections({
	x: {
		directionInverted: false,
		rotationComment: '40 for 20 tooth 2GT pulleys, 32 for 16 tooth 2GT pulleys',
		limits: (margin) => ({
			min: 0 - margin.min,
			max: config.size.x,
			endstop: 0 - margin.min,
		}),
		additionalLines: [],
	},
	y: {
		directionInverted: true,
		rotationComment: '40 for 20 tooth 2GT pulleys, 32 for 16 tooth 2GT pulleys',
		limits: (margin) => ({
			min: 0 - margin.min,
			max: config.size.y + margin.max,
			endstop: 0 - margin.min,
		}),
	},
	z: {
		directionInverted: true,
		rotationComment: '4 for TR8*4 lead screws',
		limits: {
			min: -5,
			max: config.size.z,
		},
	},
	z1: {
		directionInverted: false,
		rotationComment: '4 for TR8*4 lead screws',
	},
	extruder: {
		directionInverted: true,
		additionalLines: [
			'#pressure_advance: 0.05 # Check https://www.klipper3d.org/Pressure_Advance.html for pressure advance tuning.',
			'control: pid',
			'pid_kp: 28.413',
			'pid_ki: 1.334',
			'pid_kd: 151.300',
		],
	}
})}

#---------------------------------------------- DUAL_CARRIAGE -----------------------------------------------
# The X axis motor for the right toolhead, located at the rear right of the printer
#------------------------------------------------------------------------------------------------------------
[dual_carriage]
dir_pin: dual_carriage_dir_pin     # Add ! in front of pin name to reverse the direction of dual_carriage
rotation_distance: 40              # 40 for 20 tooth 2GT pulleys, 32 for 16 tooth 2GT pulleys
position_min: 0
position_max: 355.1
position_endstop: 355.1
safe_distance: 50

#------------------------------------------------ EXTRUDER1 -------------------------------------------------
# The extruder motor used for pushing filament through the right toolhead (T1)
#------------------------------------------------------------------------------------------------------------
[extruder1]
dir_pin: !e1_dir_pin   # Remove ! in front of pin name to reverse the direction of extruder1
rotation_distance: 4.263          # Phaetus Apus default
#pressure_advance: 0.05           # Check https://www.klipper3d.org/Pressure_Advance.html for pressure advance tuning.
control: pid
pid_kp: 28.413
pid_ki: 1.334
pid_kd: 151.300


[heater_bed]
control: pid
pid_Kp: 59.1
pid_Ki: 2.8
pid_Kd: 317

${helper.renderProbePinSection()}

${helper.renderReminders()}
`;
